<?xml version="1.0" encoding="utf-8"?>

<!--
    Copyright 2009 the original author or authors. Licensed under the Apache
    License, Version 2.0 (the "License"); you may not use this file except
    in compliance with the License. You may obtain a copy of the License at
    http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable
    law or agreed to in writing, software distributed under the License is
    distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
    KIND, either express or implied. See the License for the specific
    language governing permissions and limitations under the License.
-->

<definitions
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:ihe="urn:ihe:iti:xds-b:2007"
        xmlns:lcm="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0"
        xmlns:rs="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0"
        xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
        targetNamespace="urn:ihe:iti:xds-b:2007"
        name="DocumentRegistry">

    <documentation>IHE XDS.b Document Registry = ITI-42 adaptor = Register Document Set.b</documentation>

    <types>
        <xsd:schema elementFormDefault="qualified">
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:rs:3.0" schemaLocation="classpath:wsdl/schema/ebRS30/rs.xsd"/>
            <xsd:import namespace="urn:oasis:names:tc:ebxml-regrep:xsd:lcm:3.0" schemaLocation="classpath:wsdl/schema/ebRS30/lcm.xsd"/>
        </xsd:schema>
    </types>

    <message name="RegisterDocumentSet-b_Message">
        <documentation>Register Document Set - b</documentation>
        <part name="body" element="lcm:SubmitObjectsRequest"/>
    </message>

    <message name="RegisterDocumentSet-bResponse_Message">
        <documentation>Register Document Set - b Response</documentation>
        <part name="body" element="rs:RegistryResponse"/>
    </message>

    <portType name="DocumentRegistry_PortType">
        <operation name="DocumentRegistry_RegisterDocumentSet-b">
            <input message="ihe:RegisterDocumentSet-b_Message"
                   wsam:Action="urn:ihe:iti:2007:RegisterDocumentSet-b"/>
            <output message="ihe:RegisterDocumentSet-bResponse_Message"
                    wsam:Action="urn:ihe:iti:2007:RegisterDocumentSet-bResponse"/>
        </operation>
    </portType>

    <binding name="DocumentRegistry_Binding_Soap12" type="ihe:DocumentRegistry_PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="DocumentRegistry_RegisterDocumentSet-b">
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="DocumentRegistry_Service">
        <port name="DocumentRegistry_Port_Soap12" binding="ihe:DocumentRegistry_Binding_Soap12">
            <soap12:address location="http://servicelocation/DocumentRegistry_Service12"/>
        </port>
    </service>
</definitions>
