<?xml version="1.0" encoding="utf-8"?>
<!--
  ~ Copyright 2012 the original author or authors.
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License");
  ~ you may not use this file except in compliance with the License.
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software
  ~ distributed under the License is distributed on an "AS IS" BASIS,
  ~ WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~ See the License for the specific language governing permissions and
  ~ limitations under the License.
  -->
<definitions
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:ihe="urn:ihe:iti:xds-b:2007"
        xmlns:iherad="urn:ihe:rad:xdsi-b:2009"
        xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
        targetNamespace="urn:ihe:rad:xdsi-b:2009"
        name="DocumentRepository">

    <documentation>IHE XDS-I.b Document Repository = RAD-69 adaptor = Retrieve Imaging Document Set</documentation>

    <types>
        <xsd:schema elementFormDefault="qualified">
            <xsd:import namespace="urn:ihe:iti:xds-b:2007" schemaLocation="classpath:wsdl/schema/IHE/IHEXDSB.xsd"/>
            <xsd:import namespace="urn:ihe:rad:xdsi-b:2009" schemaLocation="classpath:wsdl/schema/IHE/IHEXDSIB.xsd"/>
        </xsd:schema>
    </types>

    <message name="RetrieveImagingDocumentSet_Message">
        <documentation>Retrieve Imaging Document Set Request</documentation>
        <part name="body" element="iherad:RetrieveImagingDocumentSetRequest"/>
    </message>

    <message name="RetrieveDocumentSetResponse_Message">
        <documentation>Retrieve Imaging Document Set Response</documentation>
        <part name="body" element="ihe:RetrieveDocumentSetResponse"/>
    </message>

    <portType name="DocumentRepository_PortType">
        <operation name="DocumentRepository_RetrieveImagingDocumentSet">
            <input message="iherad:RetrieveImagingDocumentSet_Message"
                   wsam:Action="urn:ihe:rad:2009:RetrieveImagingDocumentSet"/>
            <output message="iherad:RetrieveDocumentSetResponse_Message"
                    wsam:Action="urn:ihe:iti:2007:RetrieveDocumentSetResponse"/>
        </operation>
    </portType>

    <binding name="DocumentRepository_Binding_Soap12" type="iherad:DocumentRepository_PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="DocumentRepository_RetrieveImagingDocumentSet">
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="DocumentRepository_Service">
        <port name="DocumentRepository_Port_Soap12" binding="iherad:DocumentRepository_Binding_Soap12">
            <soap12:address location="http://servicelocation/DocumentRepository_Service12"/>
        </port>
    </service>
</definitions>
