<?xml version="1.0" encoding="utf-8"?>
<definitions name="HPDProviderInformationDirectory"
             targetNamespace="urn:ihe:iti:hpd:2010"
             xmlns:tns="urn:ihe:iti:hpd:2010"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:ch-pidd="urn:ehealth-suisse:names:tc:CS:1"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <documentation>IHE-Suisse HPD Provider Information Directory</documentation>

    <types>
        <xsd:schema targetNamespace="urn:ehealth-suisse:names:tc:CS:1">
            <xsd:include schemaLocation="../schema/PIDD.xsd"/>
        </xsd:schema>
    </types>

    <message name="ProviderInformationDownloadRequestMessage">

        <part name="body" element="ch-pidd:downloadRequest"/>
    </message>
    <message name="ProviderInformationDownloadResponseMessage">

        <part name="body" element="ch-pidd:downloadResponse"/>
    </message>

    <portType name="ProviderInformationDirectory_PortType">
        <operation name="ProviderInformationDownloadRequest">
            <input message="tns:ProviderInformationDownloadRequestMessage" wsam:Action="urn:ihe:iti:hpd:2010:ProviderInformationDownloadRequest"/>
            <output message="tns:ProviderInformationDownloadResponseMessage" wsam:Action="urn:ihe:iti:hpd:2010:ProviderInformationDownloadResponse"/>
        </operation>
    </portType>

    <binding name="ProviderInformationDirectory_Binding" type="tns:ProviderInformationDirectory_PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ProviderInformationDownloadRequest">
            <soap12:operation soapActionRequired="false"/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="ProviderInformationDirectory_Service">
        <port name="ProviderInformationDirectory_Port_Soap12" binding="tns:ProviderInformationDirectory_Binding">
            <soap12:address location="https://localhost:8080/ch-pidd"/>
        </port>
    </service>
</definitions>

