<?xml version="1.0" encoding="utf-8"?>
<definitions name="HPDProviderInformationDirectory"
             targetNamespace="urn:ihe:iti:hpd:2010"
             xmlns:tns="urn:ihe:iti:hpd:2010"
             xmlns="http://schemas.xmlsoap.org/wsdl/"
             xmlns:dsml="urn:oasis:names:tc:DSML:2:0:core"
             xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
             xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/"
             xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <documentation>IHE HPD Provider Information Directory</documentation>

    <types>
        <xsd:schema targetNamespace="urn:oasis:names:tc:DSML:2:0:core">
            <xsd:include schemaLocation="../schema/DSMLv2.xsd"/>
        </xsd:schema>
    </types>

    <message name="ProviderInformationRequestMessage">
        <documentation>Provider Information Query/Feed Request Message</documentation>
        <part name="body" element="dsml:batchRequest"/>
    </message>
    <message name="ProviderInformationResponseMessage">
        <documentation>Provider Information Query/Feed Response Message</documentation>
        <part name="body" element="dsml:batchResponse"/>
    </message>

    <portType name="ProviderInformationDirectory_PortType">
        <operation name="ProviderInformationQueryRequest">
            <input message="tns:ProviderInformationRequestMessage" wsam:Action="urn:ihe:iti:hpd:2010:ProviderInformationQuery"/>
            <output message="tns:ProviderInformationResponseMessage" wsam:Action="urn:ihe:iti:hpd:2010:ProviderInformationQueryResponse"/>
        </operation>
    </portType>

    <binding name="ProviderInformationDirectory_Binding" type="tns:ProviderInformationDirectory_PortType">
        <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <operation name="ProviderInformationQueryRequest">
            <soap12:operation soapActionRequired="false"/>
            <input>
                <soap12:body use="literal"/>
            </input>
            <output>
                <soap12:body use="literal"/>
            </output>
        </operation>
    </binding>

    <service name="ProviderInformationDirectory_Service">
        <port name="ProviderInformationDirectory_Port_Soap12" binding="tns:ProviderInformationDirectory_Binding">
            <soap12:address location="https://localhost:8080/iti-58"/>
        </port>
    </service>
</definitions>

