/**
 * _0272.java
 *
 * File generated from the voc::_0272 uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration _0272.
 *
 */

@XmlType(name = "_0272")
@XmlEnum
@XmlRootElement(name = "_0272")
public enum _0272 {
	@XmlEnumValue("0245")
	_0245("0245"),
	@XmlEnumValue("0246")
	_0246("0246"),
	@XmlEnumValue("0272")
	_0272("0272");
	
	private final String value;

    _0272(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static _0272 fromValue(String v) {
        for (_0272 c: _0272.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}