/**
 * ActAccommodationReason.java
 *
 * File generated from the voc::ActAccommodationReason uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ActAccommodationReason.
 *
 */

@XmlType(name = "ActAccommodationReason")
@XmlEnum
@XmlRootElement(name = "ActAccommodationReason")
public enum ActAccommodationReason {
	@XmlEnumValue("ACCREQNA")
	ACCREQNA("ACCREQNA"),
	@XmlEnumValue("FLRCNV")
	FLRCNV("FLRCNV"),
	@XmlEnumValue("MEDNEC")
	MEDNEC("MEDNEC"),
	@XmlEnumValue("PAT")
	PAT("PAT");
	
	private final String value;

    ActAccommodationReason(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ActAccommodationReason fromValue(String v) {
        for (ActAccommodationReason c: ActAccommodationReason.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}