/**
 * ActClassProcedure.java
 * <p>
 * File generated from the voc::ActClassProcedure uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ActClassProcedure.
 *
 */

@XmlType(name = "ActClassProcedure")
@XmlEnum
@XmlRootElement(name = "ActClassProcedure")
public enum ActClassProcedure {
	@XmlEnumValue("PROC")
	PROC("PROC"),
	@XmlEnumValue("SPECCOLLECT")
	SPECCOLLECT("SPECCOLLECT");
	
	private final String value;

    ActClassProcedure(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ActClassProcedure fromValue(String v) {
        for (ActClassProcedure c: ActClassProcedure.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}