/**
 * ActProgramTypeCode.java
 *
 * File generated from the voc::ActProgramTypeCode uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ActProgramTypeCode.
 *
 */

@XmlType(name = "ActProgramTypeCode")
@XmlEnum
@XmlRootElement(name = "ActProgramTypeCode")
public enum ActProgramTypeCode {
	@XmlEnumValue("CANPRG")
	CANPRG("CANPRG"),
	@XmlEnumValue("CHAR")
	CHAR("CHAR"),
	@XmlEnumValue("CRIME")
	CRIME("CRIME"),
	@XmlEnumValue("DENTPRG")
	DENTPRG("DENTPRG"),
	@XmlEnumValue("DISEASEPRG")
	DISEASEPRG("DISEASEPRG"),
	@XmlEnumValue("EAP")
	EAP("EAP"),
	@XmlEnumValue("ENDRENAL")
	ENDRENAL("ENDRENAL"),
	@XmlEnumValue("GOVEMP")
	GOVEMP("GOVEMP"),
	@XmlEnumValue("HIRISK")
	HIRISK("HIRISK"),
	@XmlEnumValue("HIVAIDS")
	HIVAIDS("HIVAIDS"),
	@XmlEnumValue("IND")
	IND("IND"),
	@XmlEnumValue("MANDPOL")
	MANDPOL("MANDPOL"),
	@XmlEnumValue("MENTPRG")
	MENTPRG("MENTPRG"),
	@XmlEnumValue("MILITARY")
	MILITARY("MILITARY"),
	@XmlEnumValue("PUBLICPOL")
	PUBLICPOL("PUBLICPOL"),
	@XmlEnumValue("RETIRE")
	RETIRE("RETIRE"),
	@XmlEnumValue("SAFNET")
	SAFNET("SAFNET"),
	@XmlEnumValue("SOCIAL")
	SOCIAL("SOCIAL"),
	@XmlEnumValue("SUBPRG")
	SUBPRG("SUBPRG"),
	@XmlEnumValue("SUBSIDIZ")
	SUBSIDIZ("SUBSIDIZ"),
	@XmlEnumValue("SUBSIDMC")
	SUBSIDMC("SUBSIDMC"),
	@XmlEnumValue("SUBSUPP")
	SUBSUPP("SUBSUPP"),
	@XmlEnumValue("VET")
	VET("VET"),
	@XmlEnumValue("WCBPOL")
	WCBPOL("WCBPOL");
	
	private final String value;

    ActProgramTypeCode(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ActProgramTypeCode fromValue(String v) {
        for (ActProgramTypeCode c: ActProgramTypeCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}