/**
 * ActSpecimenTransportCode.java
 *
 * File generated from the voc::ActSpecimenTransportCode uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ActSpecimenTransportCode.
 *
 */

@XmlType(name = "ActSpecimenTransportCode")
@XmlEnum
@XmlRootElement(name = "ActSpecimenTransportCode")
public enum ActSpecimenTransportCode {
	@XmlEnumValue("SREC")
	SREC("SREC"),
	@XmlEnumValue("SSTOR")
	SSTOR("SSTOR"),
	@XmlEnumValue("STRAN")
	STRAN("STRAN");
	
	private final String value;

    ActSpecimenTransportCode(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ActSpecimenTransportCode fromValue(String v) {
        for (ActSpecimenTransportCode c: ActSpecimenTransportCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}