/**
 * AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT.java
 *
 * File generated from the voc::AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT.
 *
 */

@XmlType(name = "AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT")
@XmlEnum
@XmlRootElement(name = "AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT")
public enum AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT {
	@XmlEnumValue("DUPTHPCLS")
	DUPTHPCLS("DUPTHPCLS"),
	@XmlEnumValue("DUPTHPGEN")
	DUPTHPGEN("DUPTHPGEN"),
	@XmlEnumValue("DUPTHPY")
	DUPTHPY("DUPTHPY");
	
	private final String value;

    AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT fromValue(String v) {
        for (AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT c: AdministrationDetectedIssueCodeDuplicateTherapyAlertByBOT.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}