/**
 * ArapahoGrosVentre.java
 * <p>
 * File generated from the voc::ArapahoGrosVentre uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ArapahoGrosVentre.
 *
 */

@XmlType(name = "ArapahoGrosVentre")
@XmlEnum
@XmlRootElement(name = "ArapahoGrosVentre")
public enum ArapahoGrosVentre {
	@XmlEnumValue("x-ARP")
	XARP("x-ARP"),
	@XmlEnumValue("x-ATS")
	XATS("x-ATS");
	
	private final String value;

    ArapahoGrosVentre(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ArapahoGrosVentre fromValue(String v) {
        for (ArapahoGrosVentre c: ArapahoGrosVentre.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}