/**
 * CalendarType.java
 *
 * File generated from the voc::CalendarType uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration CalendarType.
 *
 */

@XmlType(name = "CalendarType")
@XmlEnum
@XmlRootElement(name = "CalendarType")
public enum CalendarType {
	@XmlEnumValue("GREG")
	GREG("GREG");
	
	private final String value;

    CalendarType(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static CalendarType fromValue(String v) {
        for (CalendarType c: CalendarType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}