/**
 * CardClinPracticeSetting.java
 * <p>
 * File generated from the voc::CardClinPracticeSetting uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration CardClinPracticeSetting.
 *
 */

@XmlType(name = "CardClinPracticeSetting")
@XmlEnum
@XmlRootElement(name = "CardClinPracticeSetting")
public enum CardClinPracticeSetting {
	@XmlEnumValue("CARD")
	CARD("CARD"),
	@XmlEnumValue("PEDCARD")
	PEDCARD("PEDCARD");
	
	private final String value;

    CardClinPracticeSetting(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static CardClinPracticeSetting fromValue(String v) {
        for (CardClinPracticeSetting c: CardClinPracticeSetting.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}