/**
 * ChildInLaw.java
 *
 * File generated from the voc::ChildInLaw uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ChildInLaw.
 *
 */

@XmlType(name = "ChildInLaw")
@XmlEnum
@XmlRootElement(name = "ChildInLaw")
public enum ChildInLaw {
	@XmlEnumValue("CHLDINLAW")
	CHLDINLAW("CHLDINLAW"),
	@XmlEnumValue("DAUINLAW")
	DAUINLAW("DAUINLAW"),
	@XmlEnumValue("SONINLAW")
	SONINLAW("SONINLAW");
	
	private final String value;

    ChildInLaw(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ChildInLaw fromValue(String v) {
        for (ChildInLaw c: ChildInLaw.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}