/**
 * CompressionAlgorithm.java
 *
 * File generated from the voc::CompressionAlgorithm uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration CompressionAlgorithm.
 *
 */

@XmlType(name = "CompressionAlgorithm")
@XmlEnum
@XmlRootElement(name = "CompressionAlgorithm")
public enum CompressionAlgorithm {
	@XmlEnumValue("DF")
	DF("DF"),
	@XmlEnumValue("GZ")
	GZ("GZ"),
	@XmlEnumValue("Z")
	Z("Z"),
	@XmlEnumValue("ZL")
	ZL("ZL");
	
	private final String value;

    CompressionAlgorithm(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static CompressionAlgorithm fromValue(String v) {
        for (CompressionAlgorithm c: CompressionAlgorithm.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}