/**
 * ConceptGenerality.java
 * <p>
 * File generated from the voc::ConceptGenerality uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ConceptGenerality.
 *
 */

@XmlType(name = "ConceptGenerality")
@XmlEnum
@XmlRootElement(name = "ConceptGenerality")
public enum ConceptGenerality {
	@XmlEnumValue("A")
	A("A"),
	@XmlEnumValue("L")
	L("L"),
	@XmlEnumValue("S")
	S("S");
	
	private final String value;

    ConceptGenerality(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ConceptGenerality fromValue(String v) {
        for (ConceptGenerality c: ConceptGenerality.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}