/**
 * ConfidentialityByAccessKind.java
 *
 * File generated from the voc::ConfidentialityByAccessKind uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ConfidentialityByAccessKind.
 *
 */

@XmlType(name = "ConfidentialityByAccessKind")
@XmlEnum
@XmlRootElement(name = "ConfidentialityByAccessKind")
public enum ConfidentialityByAccessKind {
	@XmlEnumValue("B")
	B("B"),
	@XmlEnumValue("D")
	D("D"),
	@XmlEnumValue("I")
	I("I"),
	@XmlEnumValue("L")
	L("L"),
	@XmlEnumValue("N")
	N("N"),
	@XmlEnumValue("R")
	R("R"),
	@XmlEnumValue("V")
	V("V");
	
	private final String value;

    ConfidentialityByAccessKind(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ConfidentialityByAccessKind fromValue(String v) {
        for (ConfidentialityByAccessKind c: ConfidentialityByAccessKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}