/**
 * DataTypeCodedValue.java
 *
 * File generated from the voc::DataTypeCodedValue uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration DataTypeCodedValue.
 *
 */

@XmlType(name = "DataTypeCodedValue")
@XmlEnum
@XmlRootElement(name = "DataTypeCodedValue")
public enum DataTypeCodedValue {
	@XmlEnumValue("CV")
	CV("CV");
	
	private final String value;

    DataTypeCodedValue(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static DataTypeCodedValue fromValue(String v) {
        for (DataTypeCodedValue c: DataTypeCodedValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}