/**
 * DataTypeIntegerNumber.java
 *
 * File generated from the voc::DataTypeIntegerNumber uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration DataTypeIntegerNumber.
 *
 */

@XmlType(name = "DataTypeIntegerNumber")
@XmlEnum
@XmlRootElement(name = "DataTypeIntegerNumber")
public enum DataTypeIntegerNumber {
	@XmlEnumValue("INT")
	INT("INT");
	
	private final String value;

    DataTypeIntegerNumber(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static DataTypeIntegerNumber fromValue(String v) {
        for (DataTypeIntegerNumber c: DataTypeIntegerNumber.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}