/**
 * DataTypeSetOfHistoricalAddresses.java
 * <p>
 * File generated from the voc::DataTypeSetOfHistoricalAddresses uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration DataTypeSetOfHistoricalAddresses.
 *
 */

@XmlType(name = "DataTypeSetOfHistoricalAddresses")
@XmlEnum
@XmlRootElement(name = "DataTypeSetOfHistoricalAddresses")
public enum DataTypeSetOfHistoricalAddresses {
	@XmlEnumValue("HIST<AD>")
	HISTAD("HIST<AD>"),
	@XmlEnumValue("SET<HXIT<AD>>")
	SETHXITAD("SET<HXIT<AD>>");
	
	private final String value;

    DataTypeSetOfHistoricalAddresses(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static DataTypeSetOfHistoricalAddresses fromValue(String v) {
        for (DataTypeSetOfHistoricalAddresses c: DataTypeSetOfHistoricalAddresses.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}