/**
 * DataTypeUncertainProbabilisticConceptDescriptor.java
 *
 * File generated from the voc::DataTypeUncertainProbabilisticConceptDescriptor uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration DataTypeUncertainProbabilisticConceptDescriptor.
 *
 */

@XmlType(name = "DataTypeUncertainProbabilisticConceptDescriptor")
@XmlEnum
@XmlRootElement(name = "DataTypeUncertainProbabilisticConceptDescriptor")
public enum DataTypeUncertainProbabilisticConceptDescriptor {
	@XmlEnumValue("UVP<CD>")
	UVPCD("UVP<CD>");
	
	private final String value;

    DataTypeUncertainProbabilisticConceptDescriptor(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static DataTypeUncertainProbabilisticConceptDescriptor fromValue(String v) {
        for (DataTypeUncertainProbabilisticConceptDescriptor c: DataTypeUncertainProbabilisticConceptDescriptor.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}