/**
 * DedicatedNonClinicalLocationRoleType.java
 *
 * File generated from the voc::DedicatedNonClinicalLocationRoleType uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration DedicatedNonClinicalLocationRoleType.
 *
 */

@XmlType(name = "DedicatedNonClinicalLocationRoleType")
@XmlEnum
@XmlRootElement(name = "DedicatedNonClinicalLocationRoleType")
public enum DedicatedNonClinicalLocationRoleType {
	@XmlEnumValue("AMB")
	AMB("AMB"),
	@XmlEnumValue("DADDR")
	DADDR("DADDR"),
	@XmlEnumValue("MOBL")
	MOBL("MOBL"),
	@XmlEnumValue("PHARM")
	PHARM("PHARM");
	
	private final String value;

    DedicatedNonClinicalLocationRoleType(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static DedicatedNonClinicalLocationRoleType fromValue(String v) {
        for (DedicatedNonClinicalLocationRoleType c: DedicatedNonClinicalLocationRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}