/**
 * DoseHighDetectedIssueCode.java
 * <p>
 * File generated from the voc::DoseHighDetectedIssueCode uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration DoseHighDetectedIssueCode.
 *
 */

@XmlType(name = "DoseHighDetectedIssueCode")
@XmlEnum
@XmlRootElement(name = "DoseHighDetectedIssueCode")
public enum DoseHighDetectedIssueCode {
	@XmlEnumValue("DOSEH")
	DOSEH("DOSEH"),
	@XmlEnumValue("DOSEHIND")
	DOSEHIND("DOSEHIND"),
	@XmlEnumValue("DOSEHINDA")
	DOSEHINDA("DOSEHINDA"),
	@XmlEnumValue("DOSEHINDSA")
	DOSEHINDSA("DOSEHINDSA"),
	@XmlEnumValue("DOSEHINDW")
	DOSEHINDW("DOSEHINDW");
	
	private final String value;

    DoseHighDetectedIssueCode(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static DoseHighDetectedIssueCode fromValue(String v) {
        for (DoseHighDetectedIssueCode c: DoseHighDetectedIssueCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}