/**
 * DoseDurationLowDetectedIssueCode.java
 * <p>
 * File generated from the voc::DoseDurationLowDetectedIssueCode uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration DoseDurationLowDetectedIssueCode.
 *
 */

@XmlType(name = "DoseDurationLowDetectedIssueCode")
@XmlEnum
@XmlRootElement(name = "DoseDurationLowDetectedIssueCode")
public enum DoseDurationLowDetectedIssueCode {
	@XmlEnumValue("DOSEDURL")
	DOSEDURL("DOSEDURL"),
	@XmlEnumValue("DOSEDURLIND")
	DOSEDURLIND("DOSEDURLIND");
	
	private final String value;

    DoseDurationLowDetectedIssueCode(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static DoseDurationLowDetectedIssueCode fromValue(String v) {
        for (DoseDurationLowDetectedIssueCode c: DoseDurationLowDetectedIssueCode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}