/**
 * EntericCoatedCapsule.java
 *
 * File generated from the voc::EntericCoatedCapsule uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration EntericCoatedCapsule.
 *
 */

@XmlType(name = "EntericCoatedCapsule")
@XmlEnum
@XmlRootElement(name = "EntericCoatedCapsule")
public enum EntericCoatedCapsule {
	@XmlEnumValue("ENTCAP")
	ENTCAP("ENTCAP"),
	@XmlEnumValue("ERENTCAP")
	ERENTCAP("ERENTCAP");
	
	private final String value;

    EntericCoatedCapsule(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static EntericCoatedCapsule fromValue(String v) {
        for (EntericCoatedCapsule c: EntericCoatedCapsule.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}