/**
 * GeneralAcuteCareHospital.java
 * <p>
 * File generated from the voc::GeneralAcuteCareHospital uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration GeneralAcuteCareHospital.
 *
 */

@XmlType(name = "GeneralAcuteCareHospital")
@XmlEnum
@XmlRootElement(name = "GeneralAcuteCareHospital")
public enum GeneralAcuteCareHospital {
	@XmlEnumValue("282NC2000N")
	_282NC2000N("282NC2000N"),
	@XmlEnumValue("282NR1301N")
	_282NR1301N("282NR1301N"),
	@XmlEnumValue("282NW0100N")
	_282NW0100N("282NW0100N"),
	@XmlEnumValue("2865C1500N")
	_2865C1500N("2865C1500N"),
	@XmlEnumValue("2865M2000N")
	_2865M2000N("2865M2000N"),
	@XmlEnumValue("2865X1600N")
	_2865X1600N("2865X1600N"),
	@XmlEnumValue("GACH")
	GACH("GACH");
	
	private final String value;

    GeneralAcuteCareHospital(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static GeneralAcuteCareHospital fromValue(String v) {
        for (GeneralAcuteCareHospital c: GeneralAcuteCareHospital.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}