/**
 * HeightSurfaceAreaAlert.java
 * <p>
 * File generated from the voc::HeightSurfaceAreaAlert uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration HeightSurfaceAreaAlert.
 *
 */

@XmlType(name = "HeightSurfaceAreaAlert")
@XmlEnum
@XmlRootElement(name = "HeightSurfaceAreaAlert")
public enum HeightSurfaceAreaAlert {
	@XmlEnumValue("DOSEHINDSA")
	DOSEHINDSA("DOSEHINDSA"),
	@XmlEnumValue("DOSELINDSA")
	DOSELINDSA("DOSELINDSA");
	
	private final String value;

    HeightSurfaceAreaAlert(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static HeightSurfaceAreaAlert fromValue(String v) {
        for (HeightSurfaceAreaAlert c: HeightSurfaceAreaAlert.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}