/**
 * ICUPracticeSetting.java
 *
 * File generated from the voc::ICUPracticeSetting uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ICUPracticeSetting.
 *
 */

@XmlType(name = "ICUPracticeSetting")
@XmlEnum
@XmlRootElement(name = "ICUPracticeSetting")
public enum ICUPracticeSetting {
	@XmlEnumValue("ICU")
	ICU("ICU"),
	@XmlEnumValue("PEDICU")
	PEDICU("PEDICU"),
	@XmlEnumValue("PEDNICU")
	PEDNICU("PEDNICU");
	
	private final String value;

    ICUPracticeSetting(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ICUPracticeSetting fromValue(String v) {
        for (ICUPracticeSetting c: ICUPracticeSetting.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}