/**
 * InhalerMedicalDevice.java
 * <p>
 * File generated from the voc::InhalerMedicalDevice uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration InhalerMedicalDevice.
 *
 */

@XmlType(name = "InhalerMedicalDevice")
@XmlEnum
@XmlRootElement(name = "InhalerMedicalDevice")
public enum InhalerMedicalDevice {
	@XmlEnumValue("DSKS")
	DSKS("DSKS"),
	@XmlEnumValue("DSKUNH")
	DSKUNH("DSKUNH"),
	@XmlEnumValue("INH")
	INH("INH"),
	@XmlEnumValue("TRBINH")
	TRBINH("TRBINH");
	
	private final String value;

    InhalerMedicalDevice(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static InhalerMedicalDevice fromValue(String v) {
        for (InhalerMedicalDevice c: InhalerMedicalDevice.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}