/**
 * Injection.java
 * <p>
 * File generated from the voc::Injection uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration Injection.
 *
 */

@XmlType(name = "Injection")
@XmlEnum
@XmlRootElement(name = "Injection")
public enum Injection {
	@XmlEnumValue("AMNINJ")
	AMNINJ("AMNINJ"),
	@XmlEnumValue("BILINJ")
	BILINJ("BILINJ"),
	@XmlEnumValue("BLADINJ")
	BLADINJ("BLADINJ"),
	@XmlEnumValue("CERVINJ")
	CERVINJ("CERVINJ"),
	@XmlEnumValue("CHOLINJ")
	CHOLINJ("CHOLINJ"),
	@XmlEnumValue("ENDOSININJ")
	ENDOSININJ("ENDOSININJ"),
	@XmlEnumValue("EPIDURINJ")
	EPIDURINJ("EPIDURINJ"),
	@XmlEnumValue("EPIINJ")
	EPIINJ("EPIINJ"),
	@XmlEnumValue("EPINJSP")
	EPINJSP("EPINJSP"),
	@XmlEnumValue("EXTCORPINJ")
	EXTCORPINJ("EXTCORPINJ"),
	@XmlEnumValue("EXTRAMNINJ")
	EXTRAMNINJ("EXTRAMNINJ"),
	@XmlEnumValue("GBINJ")
	GBINJ("GBINJ"),
	@XmlEnumValue("GINGINJ")
	GINGINJ("GINGINJ"),
	@XmlEnumValue("HEMOPORT")
	HEMOPORT("HEMOPORT"),
	@XmlEnumValue("IABDINJ")
	IABDINJ("IABDINJ"),
	@XmlEnumValue("IAINJ")
	IAINJ("IAINJ"),
	@XmlEnumValue("IAINJP")
	IAINJP("IAINJP"),
	@XmlEnumValue("IAINJSP")
	IAINJSP("IAINJSP"),
	@XmlEnumValue("IARTINJ")
	IARTINJ("IARTINJ"),
	@XmlEnumValue("IBURSINJ")
	IBURSINJ("IBURSINJ"),
	@XmlEnumValue("ICARDINJ")
	ICARDINJ("ICARDINJ"),
	@XmlEnumValue("ICARDINJRP")
	ICARDINJRP("ICARDINJRP"),
	@XmlEnumValue("ICARDINJSP")
	ICARDINJSP("ICARDINJSP"),
	@XmlEnumValue("ICARINJP")
	ICARINJP("ICARINJP"),
	@XmlEnumValue("ICARTINJ")
	ICARTINJ("ICARTINJ"),
	@XmlEnumValue("ICAUDINJ")
	ICAUDINJ("ICAUDINJ"),
	@XmlEnumValue("ICAVINJ")
	ICAVINJ("ICAVINJ"),
	@XmlEnumValue("ICAVITINJ")
	ICAVITINJ("ICAVITINJ"),
	@XmlEnumValue("ICEREBINJ")
	ICEREBINJ("ICEREBINJ"),
	@XmlEnumValue("ICISTERNINJ")
	ICISTERNINJ("ICISTERNINJ"),
	@XmlEnumValue("ICORONINJ")
	ICORONINJ("ICORONINJ"),
	@XmlEnumValue("ICORONINJP")
	ICORONINJP("ICORONINJP"),
	@XmlEnumValue("ICORPCAVINJ")
	ICORPCAVINJ("ICORPCAVINJ"),
	@XmlEnumValue("IDINJ")
	IDINJ("IDINJ"),
	@XmlEnumValue("IDISCINJ")
	IDISCINJ("IDISCINJ"),
	@XmlEnumValue("IDUCTINJ")
	IDUCTINJ("IDUCTINJ"),
	@XmlEnumValue("IDURINJ")
	IDURINJ("IDURINJ"),
	@XmlEnumValue("IEPIDINJ")
	IEPIDINJ("IEPIDINJ"),
	@XmlEnumValue("IEPITHINJ")
	IEPITHINJ("IEPITHINJ"),
	@XmlEnumValue("ILESINJ")
	ILESINJ("ILESINJ"),
	@XmlEnumValue("ILUMINJ")
	ILUMINJ("ILUMINJ"),
	@XmlEnumValue("ILYMPJINJ")
	ILYMPJINJ("ILYMPJINJ"),
	@XmlEnumValue("IM")
	IM("IM"),
	@XmlEnumValue("IMD")
	IMD("IMD"),
	@XmlEnumValue("IMEDULINJ")
	IMEDULINJ("IMEDULINJ"),
	@XmlEnumValue("IMZ")
	IMZ("IMZ"),
	@XmlEnumValue("INTERMENINJ")
	INTERMENINJ("INTERMENINJ"),
	@XmlEnumValue("INTERSTITINJ")
	INTERSTITINJ("INTERSTITINJ"),
	@XmlEnumValue("IOINJ")
	IOINJ("IOINJ"),
	@XmlEnumValue("IOSSINJ")
	IOSSINJ("IOSSINJ"),
	@XmlEnumValue("IOVARINJ")
	IOVARINJ("IOVARINJ"),
	@XmlEnumValue("IPCARDINJ")
	IPCARDINJ("IPCARDINJ"),
	@XmlEnumValue("IPERINJ")
	IPERINJ("IPERINJ"),
	@XmlEnumValue("IPINJ")
	IPINJ("IPINJ"),
	@XmlEnumValue("IPLRINJ")
	IPLRINJ("IPLRINJ"),
	@XmlEnumValue("IPROSTINJ")
	IPROSTINJ("IPROSTINJ"),
	@XmlEnumValue("IPUMPINJ")
	IPUMPINJ("IPUMPINJ"),
	@XmlEnumValue("ISINJ")
	ISINJ("ISINJ"),
	@XmlEnumValue("ISTERINJ")
	ISTERINJ("ISTERINJ"),
	@XmlEnumValue("ISYNINJ")
	ISYNINJ("ISYNINJ"),
	@XmlEnumValue("ITENDINJ")
	ITENDINJ("ITENDINJ"),
	@XmlEnumValue("ITESTINJ")
	ITESTINJ("ITESTINJ"),
	@XmlEnumValue("ITHORINJ")
	ITHORINJ("ITHORINJ"),
	@XmlEnumValue("ITINJ")
	ITINJ("ITINJ"),
	@XmlEnumValue("ITUBINJ")
	ITUBINJ("ITUBINJ"),
	@XmlEnumValue("ITUMINJ")
	ITUMINJ("ITUMINJ"),
	@XmlEnumValue("ITYMPINJ")
	ITYMPINJ("ITYMPINJ"),
	@XmlEnumValue("IUINJ")
	IUINJ("IUINJ"),
	@XmlEnumValue("IUINJC")
	IUINJC("IUINJC"),
	@XmlEnumValue("IURETINJ")
	IURETINJ("IURETINJ"),
	@XmlEnumValue("IVASCINJ")
	IVASCINJ("IVASCINJ"),
	@XmlEnumValue("IVENTINJ")
	IVENTINJ("IVENTINJ"),
	@XmlEnumValue("IVESINJ")
	IVESINJ("IVESINJ"),
	@XmlEnumValue("IVINJ")
	IVINJ("IVINJ"),
	@XmlEnumValue("IVINJBOL")
	IVINJBOL("IVINJBOL"),
	@XmlEnumValue("IVITINJ")
	IVITINJ("IVITINJ"),
	@XmlEnumValue("IVPUSH")
	IVPUSH("IVPUSH"),
	@XmlEnumValue("IVRPUSH")
	IVRPUSH("IVRPUSH"),
	@XmlEnumValue("IVSPUSH")
	IVSPUSH("IVSPUSH"),
	@XmlEnumValue("PAINJ")
	PAINJ("PAINJ"),
	@XmlEnumValue("PARENTINJ")
	PARENTINJ("PARENTINJ"),
	@XmlEnumValue("PDONTINJ")
	PDONTINJ("PDONTINJ"),
	@XmlEnumValue("PDPINJ")
	PDPINJ("PDPINJ"),
	@XmlEnumValue("PDURINJ")
	PDURINJ("PDURINJ"),
	@XmlEnumValue("PNINJ")
	PNINJ("PNINJ"),
	@XmlEnumValue("PNSINJ")
	PNSINJ("PNSINJ"),
	@XmlEnumValue("RBINJ")
	RBINJ("RBINJ"),
	@XmlEnumValue("SCINJ")
	SCINJ("SCINJ"),
	@XmlEnumValue("SLESINJ")
	SLESINJ("SLESINJ"),
	@XmlEnumValue("SOFTISINJ")
	SOFTISINJ("SOFTISINJ"),
	@XmlEnumValue("SQ")
	SQ("SQ"),
	@XmlEnumValue("SUBARACHINJ")
	SUBARACHINJ("SUBARACHINJ"),
	@XmlEnumValue("SUBMUCINJ")
	SUBMUCINJ("SUBMUCINJ"),
	@XmlEnumValue("TRPLACINJ")
	TRPLACINJ("TRPLACINJ"),
	@XmlEnumValue("TRTRACHINJ")
	TRTRACHINJ("TRTRACHINJ"),
	@XmlEnumValue("URETHINJ")
	URETHINJ("URETHINJ"),
	@XmlEnumValue("URETINJ")
	URETINJ("URETINJ");
	
	private final String value;

    Injection(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static Injection fromValue(String v) {
        for (Injection c: Injection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}