/**
 * IntracerebralRoute.java
 *
 * File generated from the voc::IntracerebralRoute uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration IntracerebralRoute.
 *
 */

@XmlType(name = "IntracerebralRoute")
@XmlEnum
@XmlRootElement(name = "IntracerebralRoute")
public enum IntracerebralRoute {
	@XmlEnumValue("ICEREBINJ")
	ICEREBINJ("ICEREBINJ");
	
	private final String value;

    IntracerebralRoute(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static IntracerebralRoute fromValue(String v) {
        for (IntracerebralRoute c: IntracerebralRoute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}