/**
 * IntravascularRoute.java
 *
 * File generated from the voc::IntravascularRoute uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration IntravascularRoute.
 *
 */

@XmlType(name = "IntravascularRoute")
@XmlEnum
@XmlRootElement(name = "IntravascularRoute")
public enum IntravascularRoute {
	@XmlEnumValue("HEMODIFF")
	HEMODIFF("HEMODIFF"),
	@XmlEnumValue("HEMOPORT")
	HEMOPORT("HEMOPORT"),
	@XmlEnumValue("IVASCINFUS")
	IVASCINFUS("IVASCINFUS"),
	@XmlEnumValue("IVASCINJ")
	IVASCINJ("IVASCINJ");
	
	private final String value;

    IntravascularRoute(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static IntravascularRoute fromValue(String v) {
        for (IntravascularRoute c: IntravascularRoute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}