/**
 * IntracoronaryInjection.java
 *
 * File generated from the voc::IntracoronaryInjection uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration IntracoronaryInjection.
 *
 */

@XmlType(name = "IntracoronaryInjection")
@XmlEnum
@XmlRootElement(name = "IntracoronaryInjection")
public enum IntracoronaryInjection {
	@XmlEnumValue("ICORONINJ")
	ICORONINJ("ICORONINJ"),
	@XmlEnumValue("ICORONINJP")
	ICORONINJP("ICORONINJP");
	
	private final String value;

    IntracoronaryInjection(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static IntracoronaryInjection fromValue(String v) {
        for (IntracoronaryInjection c: IntracoronaryInjection.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}