/**
 * IntravenousInfusion.java
 *
 * File generated from the voc::IntravenousInfusion uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration IntravenousInfusion.
 *
 */

@XmlType(name = "IntravenousInfusion")
@XmlEnum
@XmlRootElement(name = "IntravenousInfusion")
public enum IntravenousInfusion {
	@XmlEnumValue("IV")
	IV("IV"),
	@XmlEnumValue("IVC")
	IVC("IVC"),
	@XmlEnumValue("IVCC")
	IVCC("IVCC"),
	@XmlEnumValue("IVCI")
	IVCI("IVCI"),
	@XmlEnumValue("PCA")
	PCA("PCA");
	
	private final String value;

    IntravenousInfusion(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static IntravenousInfusion fromValue(String v) {
        for (IntravenousInfusion c: IntravenousInfusion.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}