/**
 * IntraluminalRoute.java
 *
 * File generated from the voc::IntraluminalRoute uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration IntraluminalRoute.
 *
 */

@XmlType(name = "IntraluminalRoute")
@XmlEnum
@XmlRootElement(name = "IntraluminalRoute")
public enum IntraluminalRoute {
	@XmlEnumValue("ILUMINJ")
	ILUMINJ("ILUMINJ"),
	@XmlEnumValue("ILUMTA")
	ILUMTA("ILUMTA");
	
	private final String value;

    IntraluminalRoute(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static IntraluminalRoute fromValue(String v) {
        for (IntraluminalRoute c: IntraluminalRoute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}