/**
 * IntracavernosalRoute.java
 * <p>
 * File generated from the voc::IntracavernosalRoute uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration IntracavernosalRoute.
 *
 */

@XmlType(name = "IntracavernosalRoute")
@XmlEnum
@XmlRootElement(name = "IntracavernosalRoute")
public enum IntracavernosalRoute {
	@XmlEnumValue("ICAVINJ")
	ICAVINJ("ICAVINJ");
	
	private final String value;

    IntracavernosalRoute(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static IntracavernosalRoute fromValue(String v) {
        for (IntracavernosalRoute c: IntracavernosalRoute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}