/**
 * MilitaryRoleType.java
 *
 * File generated from the voc::MilitaryRoleType uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration MilitaryRoleType.
 *
 */

@XmlType(name = "MilitaryRoleType")
@XmlEnum
@XmlRootElement(name = "MilitaryRoleType")
public enum MilitaryRoleType {
	@XmlEnumValue("ACTMIL")
	ACTMIL("ACTMIL"),
	@XmlEnumValue("MIL")
	MIL("MIL"),
	@XmlEnumValue("RETMIL")
	RETMIL("RETMIL"),
	@XmlEnumValue("VET")
	VET("VET");
	
	private final String value;

    MilitaryRoleType(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static MilitaryRoleType fromValue(String v) {
        for (MilitaryRoleType c: MilitaryRoleType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}