/**
 * ObservationSocioEconomicStatusValue.java
 * <p>
 * File generated from the voc::ObservationSocioEconomicStatusValue uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration ObservationSocioEconomicStatusValue.
 *
 */

@XmlType(name = "ObservationSocioEconomicStatusValue")
@XmlEnum
@XmlRootElement(name = "ObservationSocioEconomicStatusValue")
public enum ObservationSocioEconomicStatusValue {
	@XmlEnumValue("ABUSE")
	ABUSE("ABUSE"),
	@XmlEnumValue("HMLESS")
	HMLESS("HMLESS"),
	@XmlEnumValue("ILGIM")
	ILGIM("ILGIM"),
	@XmlEnumValue("INCAR")
	INCAR("INCAR"),
	@XmlEnumValue("PROB")
	PROB("PROB"),
	@XmlEnumValue("REFUG")
	REFUG("REFUG"),
	@XmlEnumValue("SOECSTAT")
	SOECSTAT("SOECSTAT"),
	@XmlEnumValue("UNEMPL")
	UNEMPL("UNEMPL");
	
	private final String value;

    ObservationSocioEconomicStatusValue(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static ObservationSocioEconomicStatusValue fromValue(String v) {
        for (ObservationSocioEconomicStatusValue c: ObservationSocioEconomicStatusValue.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}