/**
 * OrderedListStyle.java
 *
 * File generated from the voc::OrderedListStyle uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration OrderedListStyle.
 *
 */

@XmlType(name = "OrderedListStyle")
@XmlEnum
@XmlRootElement(name = "OrderedListStyle")
public enum OrderedListStyle {
	@XmlEnumValue("Arabic")
	ARABIC("Arabic"),
	@XmlEnumValue("BigAlpha")
	BIGALPHA("BigAlpha"),
	@XmlEnumValue("BigRoman")
	BIGROMAN("BigRoman"),
	@XmlEnumValue("LittleAlpha")
	LITTLEALPHA("LittleAlpha"),
	@XmlEnumValue("LittleRoman")
	LITTLEROMAN("LittleRoman");
	
	private final String value;

    OrderedListStyle(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static OrderedListStyle fromValue(String v) {
        for (OrderedListStyle c: OrderedListStyle.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}