/**
 * OtherServiceProviderSpecialistHIPAA.java
 * <p>
 * File generated from the voc::OtherServiceProviderSpecialistHIPAA uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration OtherServiceProviderSpecialistHIPAA.
 *
 */

@XmlType(name = "OtherServiceProviderSpecialistHIPAA")
@XmlEnum
@XmlRootElement(name = "OtherServiceProviderSpecialistHIPAA")
public enum OtherServiceProviderSpecialistHIPAA {
	@XmlEnumValue("1744G0900N")
	_1744G0900N("1744G0900N"),
	@XmlEnumValue("1744P3200N")
	_1744P3200N("1744P3200N"),
	@XmlEnumValue("1744R1102N")
	_1744R1102N("1744R1102N"),
	@XmlEnumValue("1744R1103N")
	_1744R1103N("1744R1103N");
	
	private final String value;

    OtherServiceProviderSpecialistHIPAA(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static OtherServiceProviderSpecialistHIPAA fromValue(String v) {
        for (OtherServiceProviderSpecialistHIPAA c: OtherServiceProviderSpecialistHIPAA.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}