/**
 * RaceAmericanIndianPima.java
 *
 * File generated from the voc::RaceAmericanIndianPima uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration RaceAmericanIndianPima.
 *
 */

@XmlType(name = "RaceAmericanIndianPima")
@XmlEnum
@XmlRootElement(name = "RaceAmericanIndianPima")
public enum RaceAmericanIndianPima {
	@XmlEnumValue("1456-3")
	_14563("1456-3"),
	@XmlEnumValue("1457-1")
	_14571("1457-1"),
	@XmlEnumValue("1458-9")
	_14589("1458-9");
	
	private final String value;

    RaceAmericanIndianPima(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static RaceAmericanIndianPima fromValue(String v) {
        for (RaceAmericanIndianPima c: RaceAmericanIndianPima.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}