/**
 * RaceAmericanIndianCalifornia.java
 * <p>
 * File generated from the voc::RaceAmericanIndianCalifornia uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration RaceAmericanIndianCalifornia.
 *
 */

@XmlType(name = "RaceAmericanIndianCalifornia")
@XmlEnum
@XmlRootElement(name = "RaceAmericanIndianCalifornia")
public enum RaceAmericanIndianCalifornia {
	@XmlEnumValue("1053-8")
	_10538("1053-8"),
	@XmlEnumValue("1054-6")
	_10546("1054-6"),
	@XmlEnumValue("1055-3")
	_10553("1055-3"),
	@XmlEnumValue("1056-1")
	_10561("1056-1"),
	@XmlEnumValue("1057-9")
	_10579("1057-9"),
	@XmlEnumValue("1058-7")
	_10587("1058-7"),
	@XmlEnumValue("1059-5")
	_10595("1059-5"),
	@XmlEnumValue("1060-3")
	_10603("1060-3"),
	@XmlEnumValue("1061-1")
	_10611("1061-1"),
	@XmlEnumValue("1062-9")
	_10629("1062-9"),
	@XmlEnumValue("1063-7")
	_10637("1063-7"),
	@XmlEnumValue("1064-5")
	_10645("1064-5"),
	@XmlEnumValue("1065-2")
	_10652("1065-2"),
	@XmlEnumValue("1066-0")
	_10660("1066-0");
	
	private final String value;

    RaceAmericanIndianCalifornia(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static RaceAmericanIndianCalifornia fromValue(String v) {
        for (RaceAmericanIndianCalifornia c: RaceAmericanIndianCalifornia.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}