/**
 * RaceBlackOrAfricanAmerican.java
 * <p>
 * File generated from the voc::RaceBlackOrAfricanAmerican uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration RaceBlackOrAfricanAmerican.
 *
 */

@XmlType(name = "RaceBlackOrAfricanAmerican")
@XmlEnum
@XmlRootElement(name = "RaceBlackOrAfricanAmerican")
public enum RaceBlackOrAfricanAmerican {
	@XmlEnumValue("2054-5")
	_20545("2054-5"),
	@XmlEnumValue("2056-0")
	_20560("2056-0"),
	@XmlEnumValue("2058-6")
	_20586("2058-6"),
	@XmlEnumValue("2060-2")
	_20602("2060-2"),
	@XmlEnumValue("2061-0")
	_20610("2061-0"),
	@XmlEnumValue("2062-8")
	_20628("2062-8"),
	@XmlEnumValue("2063-6")
	_20636("2063-6"),
	@XmlEnumValue("2064-4")
	_20644("2064-4"),
	@XmlEnumValue("2065-1")
	_20651("2065-1"),
	@XmlEnumValue("2066-9")
	_20669("2066-9"),
	@XmlEnumValue("2067-7")
	_20677("2067-7"),
	@XmlEnumValue("2068-5")
	_20685("2068-5"),
	@XmlEnumValue("2069-3")
	_20693("2069-3"),
	@XmlEnumValue("2070-1")
	_20701("2070-1"),
	@XmlEnumValue("2071-9")
	_20719("2071-9"),
	@XmlEnumValue("2072-7")
	_20727("2072-7"),
	@XmlEnumValue("2073-5")
	_20735("2073-5"),
	@XmlEnumValue("2074-3")
	_20743("2074-3"),
	@XmlEnumValue("2075-0")
	_20750("2075-0");
	
	private final String value;

    RaceBlackOrAfricanAmerican(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static RaceBlackOrAfricanAmerican fromValue(String v) {
        for (RaceBlackOrAfricanAmerican c: RaceBlackOrAfricanAmerican.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}