/**
 * RaceAmericanIndianSacFox.java
 * <p>
 * File generated from the voc::RaceAmericanIndianSacFox uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration RaceAmericanIndianSacFox.
 *
 */

@XmlType(name = "RaceAmericanIndianSacFox")
@XmlEnum
@XmlRootElement(name = "RaceAmericanIndianSacFox")
public enum RaceAmericanIndianSacFox {
	@XmlEnumValue("1551-1")
	_15511("1551-1"),
	@XmlEnumValue("1552-9")
	_15529("1552-9"),
	@XmlEnumValue("1553-7")
	_15537("1553-7"),
	@XmlEnumValue("1554-5")
	_15545("1554-5");
	
	private final String value;

    RaceAmericanIndianSacFox(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static RaceAmericanIndianSacFox fromValue(String v) {
        for (RaceAmericanIndianSacFox c: RaceAmericanIndianSacFox.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}