/**
 * RaceAlaskanNativeAleutAlutiiq.java
 * <p>
 * File generated from the voc::RaceAlaskanNativeAleutAlutiiq uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration RaceAlaskanNativeAleutAlutiiq.
 *
 */

@XmlType(name = "RaceAlaskanNativeAleutAlutiiq")
@XmlEnum
@XmlRootElement(name = "RaceAlaskanNativeAleutAlutiiq")
public enum RaceAlaskanNativeAleutAlutiiq {
	@XmlEnumValue("1968-7")
	_19687("1968-7"),
	@XmlEnumValue("1969-5")
	_19695("1969-5"),
	@XmlEnumValue("1970-3")
	_19703("1970-3");
	
	private final String value;

    RaceAlaskanNativeAleutAlutiiq(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static RaceAlaskanNativeAleutAlutiiq fromValue(String v) {
        for (RaceAlaskanNativeAleutAlutiiq c: RaceAlaskanNativeAleutAlutiiq.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}