/**
 * RaceAmericanIndianYurok.java
 *
 * File generated from the voc::RaceAmericanIndianYurok uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration RaceAmericanIndianYurok.
 *
 */

@XmlType(name = "RaceAmericanIndianYurok")
@XmlEnum
@XmlRootElement(name = "RaceAmericanIndianYurok")
public enum RaceAmericanIndianYurok {
	@XmlEnumValue("1732-7")
	_17327("1732-7"),
	@XmlEnumValue("1733-5")
	_17335("1733-5");
	
	private final String value;

    RaceAmericanIndianYurok(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static RaceAmericanIndianYurok fromValue(String v) {
        for (RaceAmericanIndianYurok c: RaceAmericanIndianYurok.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}