/**
 * Rinse.java
 *
 * File generated from the voc::Rinse uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration Rinse.
 *
 */

@XmlType(name = "Rinse")
@XmlEnum
@XmlRootElement(name = "Rinse")
public enum Rinse {
	@XmlEnumValue("DENRINSE")
	DENRINSE("DENRINSE"),
	@XmlEnumValue("ORRINSE")
	ORRINSE("ORRINSE");
	
	private final String value;

    Rinse(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static Rinse fromValue(String v) {
        for (Rinse c: Rinse.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}