/**
 * RoleClassInactiveIngredient.java
 *
 * File generated from the voc::RoleClassInactiveIngredient uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration RoleClassInactiveIngredient.
 *
 */

@XmlType(name = "RoleClassInactiveIngredient")
@XmlEnum
@XmlRootElement(name = "RoleClassInactiveIngredient")
public enum RoleClassInactiveIngredient {
	@XmlEnumValue("COLR")
	COLR("COLR"),
	@XmlEnumValue("FLVR")
	FLVR("FLVR"),
	@XmlEnumValue("IACT")
	IACT("IACT"),
	@XmlEnumValue("PRSV")
	PRSV("PRSV"),
	@XmlEnumValue("STBL")
	STBL("STBL");
	
	private final String value;

    RoleClassInactiveIngredient(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static RoleClassInactiveIngredient fromValue(String v) {
        for (RoleClassInactiveIngredient c: RoleClassInactiveIngredient.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}