/**
 * SublesionalRoute.java
 * <p>
 * File generated from the voc::SublesionalRoute uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration SublesionalRoute.
 *
 */

@XmlType(name = "SublesionalRoute")
@XmlEnum
@XmlRootElement(name = "SublesionalRoute")
public enum SublesionalRoute {
	@XmlEnumValue("SLESINJ")
	SLESINJ("SLESINJ");
	
	private final String value;

    SublesionalRoute(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static SublesionalRoute fromValue(String v) {
        for (SublesionalRoute c: SublesionalRoute.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}