/**
 * TechnicianHealthInformationProviderCodes.java
 * <p>
 * File generated from the voc::TechnicianHealthInformationProviderCodes uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration TechnicianHealthInformationProviderCodes.
 *
 */

@XmlType(name = "TechnicianHealthInformationProviderCodes")
@XmlEnum
@XmlRootElement(name = "TechnicianHealthInformationProviderCodes")
public enum TechnicianHealthInformationProviderCodes {
	@XmlEnumValue("247000000X")
	_247000000X("247000000X"),
	@XmlEnumValue("2470A2800X")
	_2470A2800X("2470A2800X");
	
	private final String value;

    TechnicianHealthInformationProviderCodes(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static TechnicianHealthInformationProviderCodes fromValue(String v) {
        for (TechnicianHealthInformationProviderCodes c: TechnicianHealthInformationProviderCodes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}