/**
 * Tepiman.java
 * <p>
 * File generated from the voc::Tepiman uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration Tepiman.
 *
 */

@XmlType(name = "Tepiman")
@XmlEnum
@XmlRootElement(name = "Tepiman")
public enum Tepiman {
	@XmlEnumValue("x-PAP")
	XPAP("x-PAP");
	
	private final String value;

    Tepiman(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static Tepiman fromValue(String v) {
        for (Tepiman c: Tepiman.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}