/**
 * UnitOfMeasurePrefixInsens.java
 *
 * File generated from the voc::UnitOfMeasurePrefixInsens uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration UnitOfMeasurePrefixInsens.
 *
 */

@XmlType(name = "UnitOfMeasurePrefixInsens")
@XmlEnum
@XmlRootElement(name = "UnitOfMeasurePrefixInsens")
public enum UnitOfMeasurePrefixInsens {
	@XmlEnumValue("A")
	A("A"),
	@XmlEnumValue("C")
	C("C"),
	@XmlEnumValue("D")
	D("D"),
	@XmlEnumValue("DA")
	DA("DA"),
	@XmlEnumValue("EX")
	EX("EX"),
	@XmlEnumValue("F")
	F("F"),
	@XmlEnumValue("GA")
	GA("GA"),
	@XmlEnumValue("GIB")
	GIB("GIB"),
	@XmlEnumValue("H")
	H("H"),
	@XmlEnumValue("K")
	K("K"),
	@XmlEnumValue("KIB")
	KIB("KIB"),
	@XmlEnumValue("M")
	M("M"),
	@XmlEnumValue("MA")
	MA("MA"),
	@XmlEnumValue("MIB")
	MIB("MIB"),
	@XmlEnumValue("N")
	N("N"),
	@XmlEnumValue("P")
	P("P"),
	@XmlEnumValue("PT")
	PT("PT"),
	@XmlEnumValue("TIB")
	TIB("TIB"),
	@XmlEnumValue("TR")
	TR("TR"),
	@XmlEnumValue("U")
	U("U"),
	@XmlEnumValue("YA")
	YA("YA"),
	@XmlEnumValue("YO")
	YO("YO"),
	@XmlEnumValue("ZA")
	ZA("ZA"),
	@XmlEnumValue("ZO")
	ZO("ZO");
	
	private final String value;

    UnitOfMeasurePrefixInsens(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static UnitOfMeasurePrefixInsens fromValue(String v) {
        for (UnitOfMeasurePrefixInsens c: UnitOfMeasurePrefixInsens.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}