/**
 * Wintuan.java
 * <p>
 * File generated from the voc::Wintuan uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration Wintuan.
 *
 */

@XmlType(name = "Wintuan")
@XmlEnum
@XmlRootElement(name = "Wintuan")
public enum Wintuan {
	@XmlEnumValue("x-WIT")
	XWIT("x-WIT");
	
	private final String value;

    Wintuan(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static Wintuan fromValue(String v) {
        for (Wintuan c: Wintuan.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}