/**
 * XActStatusActiveSuspended.java
 *
 * File generated from the voc::XActStatusActiveSuspended uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration XActStatusActiveSuspended.
 *
 */

@XmlType(name = "XActStatusActiveSuspended")
@XmlEnum
@XmlRootElement(name = "XActStatusActiveSuspended")
public enum XActStatusActiveSuspended {
	@XmlEnumValue("active")
	ACTIVE("active"),
	@XmlEnumValue("suspended")
	SUSPENDED("suspended");
	
	private final String value;

    XActStatusActiveSuspended(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static XActStatusActiveSuspended fromValue(String v) {
        for (XActStatusActiveSuspended c: XActStatusActiveSuspended.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}