/**
 * XSubstitutionConditionNoneOrUnconditional.java
 * <p>
 * File generated from the voc::XSubstitutionConditionNoneOrUnconditional uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.voc;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration XSubstitutionConditionNoneOrUnconditional.
 *
 */

@XmlType(name = "XSubstitutionConditionNoneOrUnconditional")
@XmlEnum
@XmlRootElement(name = "XSubstitutionConditionNoneOrUnconditional")
public enum XSubstitutionConditionNoneOrUnconditional {
	@XmlEnumValue("NOSUB")
	NOSUB("NOSUB"),
	@XmlEnumValue("UNCOND")
	UNCOND("UNCOND");
	
	private final String value;

    XSubstitutionConditionNoneOrUnconditional(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static XSubstitutionConditionNoneOrUnconditional fromValue(String v) {
        for (XSubstitutionConditionNoneOrUnconditional c: XSubstitutionConditionNoneOrUnconditional.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}