/**
 * PRPAMT201302UV02MemberIdUpdateMode.java
 *
 * File generated from the prpamt201302UV02::PRPAMT201302UV02MemberIdUpdateMode uml Enumeration
 * Generated by IHE - europe, gazelle team
 */
package net.ihe.gazelle.hl7v3.prpamt201302UV02;

import jakarta.xml.bind.annotation.XmlEnum;
import jakarta.xml.bind.annotation.XmlEnumValue;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;
/**
 * Description of the enumeration PRPAMT201302UV02MemberIdUpdateMode.
 *
 */

@XmlType(name = "PRPAMT201302UV02MemberIdUpdateMode")
@XmlEnum
@XmlRootElement(name = "PRPAMT201302UV02MemberIdUpdateMode")
public enum PRPAMT201302UV02MemberIdUpdateMode {
	@XmlEnumValue("A")
	A("A"),
	@XmlEnumValue("N")
	N("N");
	
	private final String value;

    PRPAMT201302UV02MemberIdUpdateMode(String v) {
        value = v;
    }
    
     public String value() {
        return value;
    }

    public static PRPAMT201302UV02MemberIdUpdateMode fromValue(String v) {
        for (PRPAMT201302UV02MemberIdUpdateMode c: PRPAMT201302UV02MemberIdUpdateMode.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }
	
}