name: Build IPF with Java 17

on: [push, pull_request, workflow_dispatch]

env:
  MAVEN_OPTS: -Xmx2048m

# on download timeouts, consider to disable connection pooling
# -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3
# or consider to restrict the ttl
#  -Dmaven.wagon.httpconnectionManager.ttlSeconds=120

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java 17 build
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
          server-id: ossrh
          server-username: ${{ secrets.nexus_username }}
          server-password: ${{ secrets.nexus_password }}
          gpg-private-key: ${{ secrets.gpg_private_key }}
          gpg-passphrase: ${{ secrets.gpg_passphrase }}

      - name: Build with Maven
        run: mvn -B clean package --file pom.xml

      - name: Submit Dependency Snapshot
        uses: advanced-security/maven-dependency-submission-action@v5
        with:
          ignore-maven-wrapper: true

      - name: Deploy to Sonatype
        if: github.ref == 'refs/heads/main'
        run: mvn -B deploy -DskipTests
